- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiver.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiverTest.java
- src/test/java/uk/gov/ons/census/fwmtadapter/util/RabbitQueueHelper.java
Refusal notifications sent from FWMT should not be sent back
Refusal notifications are filtered out to FWMT by channel
checkout this branch and build local docker image.
run using docker-dev
run tests
[Trello](https://trello.com/c/jHFIWB9G/1002-refusals-from-field-not-being-filtered-out)
> Fix refusal to field message

- src/main/java/uk/gov/ons/census/fwmtadapter/client/CaseClient.java
- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/CaseContainer.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/CaseIdAddressTypeDto.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/EventDTO.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/field/ActionCancel.java
- src/main/java/uk/gov/ons/census/fwmtadapter/services/ReceiptService.java
- src/test/java/uk/gov/ons/census/fwmtadapter/client/CaseClientTest.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiverTest.java
- src/test/java/uk/gov/ons/census/fwmtadapter/services/ReceiptServiceTest.java
ActionCancel msg was missing addressType
Added AddressType to ActionCancel msg
This requires extra/different calls to case-api
Get the related ATs and case-api 
https://github.com/ONSdigital/census-rm-case-api/pull/23
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/104
https://trello.com/c/B7P71yDJ/1042-cancel-refusal-message-to-the-field-is-incorrect
> 1042 fix action cancel message

- Dockerfile
- src/main/java/uk/gov/ons/census/fwmtadapter/config/MessageErrorHandler.java
We can't handle messages from FWMT due to strict JSON checking
Disabled strict JSON checking.
Hard to reproduce, but try this message:
```
{"event":{"type":"FULFILMENT_REQUESTED","source":"FIELDWORK_GATEWAY","channel":"FIELD","dateTime":"2019-09-13T14:22:34.327Z","transactionId":"3287c518-1898-406c-b55e-1e6138678550"},"payload":{"fulfilmentRequest":{"fulfilmentCode":"P_OR_H1","caseId":"02606dca-7f75-e911-abc4-0003ff39541c","address":{},"contact":{"title":null,"forename":null,"surname":null,"telNo":null}}}}
```
Trello: https://trello.com/c/MKGPgxP8
> Fix for strict JSON checking

- Dockerfile
Running docker containers in root is a security concern so there should be a user that's created that the container can use instead. 
- Added a non-root user
- Updated dockerfile layout
- Removed JAVA_OPTS instead pass in JAVA_TOOL_OPTIONS in compose and kubernetes 
- Run mvn clean install
- Run in docker dev environment with other prs
- Run in kubernetes environment with other prs
[Trello](https://trello.com/c/dUT7y0TW)
> Making dockerfile non root

- src/main/java/uk/gov/ons/census/fwmtadapter/config/MessageConsumerConfig.java
- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/ManagedMessageRecoverer.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ManagedMessageRecovererTest.java
- src/test/resources/definitions.json
We need to make RabbitMQ responsible for routing bad messages to a DLQ instead of manually doing this in our application code. This PR makes use of `AmqpRejectAndDontRequeueException` to reject a bad message, allowing Rabbit to take care of routing and redelivering that message.
* Reject the message by throwing an exception
* Remove retry exchange from code 
* Suppress 'noisy' stack trace logging at warning level when the exception is thrown
*  Update tests and test queue config
Build this branch, checkout the [docker-dev PR](https://github.com/ONSdigital/census-rm-docker-dev/pull/40) and post a bad message to a queue this service consumes from. Check the message is redelivered continuously.
https://trello.com/c/hG9Mi8tA/315-rabbit-message-persistence-dlq-config-8
> Rabbit msg persistence dlq config

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/UacUpdatedReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/utility/QuestionnaireTypeHelper.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/UacUpdatedReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/UacUpdatedReceiverTest.java
- src/test/java/uk/gov/ons/census/fwmtadapter/util/QuestionnaireTypeHelperTest.java
When we receive a PQRS receipt for a continuation form we need ensure that fieldwork are not sent an Action Cancel instruction from this so that follow-ups can continue until the main form is receipted. 
* Validation to ensure continuation questionnaire types are ignored
* Added and updated tests
Ensure tests all pass and run acceptance tests from link below
https://trello.com/c/cvCv6U1R/499-do-not-send-a-cancel-message-when-a-continuation-form-is-completed-3
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/159
> Ignore cancel msg for continuation QID

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/CaseContainerDto.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/RefusalReceiverTest.java
We can safely ignore any refusal message which comes into the fieldwork-adapter which is from a non-Field channel for an estab address-level case. 
Add check after retrieving the case from the case-api to see if the address level is `E`.
Run maven build and acceptance tests against the links in this PR. There should be no regression.
https://trello.com/c/i0aebEJC/534-handle-ce-and-spg-refusals-for-estab-address-level-cases-5
https://github.com/ONSdigital/census-rm-case-processor/pull/103
> Handle estab address level refusal & tests

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/FieldworkFollowup.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiverTest.java
We need to add `handDeliver` bool flag on each of our outgoing Action Instruction `CREATE` messages to Field. 
Updated the receiver to include `handDeliver` in the sent msg
Check build, run ATs against links below
https://trello.com/c/774V6fGU/580-add-handdelivery-flag-to-casecreated-and-caseupdated-events-and-case-api-8
https://github.com/ONSdigital/census-rm-ddl/pull/38
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/191
https://github.com/ONSdigital/census-rm-action-worker/pull/10
https://github.com/ONSdigital/census-rm-case-processor/pull/112
https://github.com/ONSdigital/census-rm-action-scheduler/pull/65
> RMC-317: Add handDelivery on outbound messages

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtCloseActionInstruction.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiverTest.java
We should drop caseRef and populate surveyName to match with the expected interface with FWMT.
* Populate survey name on field close message
* Remove case ref from field close message
* Update tests
Build and run with linked AT branch
https://trello.com/c/nwGrBR4Q/639-tweak-outbound-fwmt-close-msg-to-match-interface
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/200
> Populate survey name on field close message

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtCreateActionInstruction.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiverTest.java
We want to drive FWMT via regular RM events. Case Processor was re-using the mechanism that Action Worker uses to send messages directly to Fieldwork Adapter, so we wanted to refactor that away and only use the regular CaseCreated RM event.
Got rid of any and every reference to the old direct message. Ensured that a CaseCreated RM event is emitted when a CCS case is created.
Run the ATs. There should be zero regression.
Trello: https://trello.com/c/ONAETtD2
> Handle FWMT CREATE from CaseCreated RM message

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtCloseActionInstruction.java
We don't want to publish both an UPDATE and a CLOSE simultaneously when a CE Unit has reached its expected count, because we can't guarantee order of delivery.
Added actual & expected counts to CLOSE messages to FWMT.
Run ATs. Zero regression.
Trello: https://trello.com/c/GapIaH4L
> Include CE exected and actual responses on CLOSE

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiver.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiverTest.java
We're now sending whatever data we have instead of conditioning on case type.
* Remove CE check on secure establishment field
* Add test for SPG type cases
Build and run linked AT branch.
https://trello.com/c/ELwJGrfA/716-rmc-341-check-spg-cases-against-new-cesecure-column-5
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/215
> Remove CE check on secure establishment field

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiver.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiverTest.java
The secure estab field was not being set on scheduled FIELD followup messages
* Set secure estab field whenever present on followup messages
Build and run linked AT's
https://trello.com/c/mzeiV7JC/750-spg-cases-not-sending-secure-estab-to-field
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/218
> Set secure estab field on all cases

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/ActionInstructionType.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtCancelActionInstruction.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiverTest.java
Better wording - less ambiguous 
Any reference to a CLOSE event has been changed to CANCEL
Changed name of FwmtCloseActionInstruction to FwmtCancelActionInstruction
Clone branch and build/test it
https://trello.com/c/3PljKzC2/770-change-field-close-message-to-cancels-5
> Changed CLOSE to CANCEL

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/Metadata.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtActionInstruction.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseUpdatedReceiverTest.java
For the blank questionnaire feature we need to be able to send this field to FWMT in the `UPDATE` message.
* Pass blank questionnaire field through
Build and run with linked services and run branch AT's
https://trello.com/c/EmrziSj3/439-rmc-173-blank-questionnaire-returned-21
https://github.com/ONSdigital/census-rm-fieldwork-adapter/pull/38
https://github.com/ONSdigital/census-rm-case-processor/pull/128
https://github.com/ONSdigital/census-rm-ddl/pull/47
https://github.com/ONSdigital/census-rm-pubsub/pull/40
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/222
> RMC-173 Blank Questionnaires Revenge

- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/Address.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/FieldworkFollowup.java
ARID is dead. Long live ARID. May estab UPRN have a long and victorious reign.
ARID has been removed. Estab ARID has been usurped by Estab UPRN.
Run the ATs along with all the other PRs on the ticket.
Trello: https://trello.com/c/zm2Ssvnn
> Remove arid

- src/main/java/uk/gov/ons/census/fwmtadapter/config/MessageConsumerConfig.java
- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/CaseReceiver.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseReceiverTest.java
Rename a receiver whose name had become stale
Renamed CaseUpdated to CaseReceiver Channel
test it and as part of this ticket with the ATs, should also work with Master
https://trello.com/c/9WC8hFnx/706-am1-part-3-new-address-notify-field-5
> rename caseUpdated to caseReceiver

- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/CollectionCase.java
New fields in CASE_UPDATED and CASE_CREATED events
New fields added
Build other repos on card and run ATs
https://trello.com/c/n6FwePKv/1052-waiting-on-action-processor-casecreated-caseupdated-events-should-contain-the-createddatetime-field-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CATD&title=Response+Management+Event+Dictionary
> Add createdDateTime and lastUpdated fields

- src/main/java/uk/gov/ons/census/fwmtadapter/client/ExceptionManagerClient.java
- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/ManagedMessageRecoverer.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/ExceptionReport.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ManagedMessageRecovererTest.java
When we get errors like null pointer exceptions, it's often unclear where exactly in the code things have gone wrong. The stacktrace has the detail, but we don't log stacktraces by default, and stack traces are often laborious to trawl through.
Added code to trawl the stacktrace and extract the 'root cause' in our code of where the NPE or other type of exception originated from, which should allow us to more quickly diagnose & fix problems.
Send in a bad message (missing some mandatory data, for example) and check the logs - there should be details about the line of code which threw the exception (NOT the cause... the RESULT of bad data being sent into RM which shouldn't happen but does happen when we're testing).
Trello: https://trello.com/c/DQgYqRA8
> Log useful stacktrace line

- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/Event.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/FieldworkFollowup.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtActionInstruction.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtCancelActionInstruction.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseReceiverIT.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseReceiverTest.java
Now using the UUID data type for UUID data.
Changes to a few DTOs and tests
Build it and run it against the acceptance tests (master), with use-UUID-type-for-UUID-data branches of DDL, case-processor, case-api, action-scheduler, action-worker, action-processor and notify-processor
https://trello.com/c/r9qwqhaS
> Use UUID data type for UUID data

- src/main/java/uk/gov/ons/census/fwmtadapter/config/MessageConsumerConfig.java
- src/main/resources/application.yml
We saw a problem with Case Processor processing a Rabbit message more than once. This seemed to be due to the Spring retry code, but we can't be certain.
Reduced retry count to 1 for failed rabbit messages.
Zero regression.
Trello: https://trello.com/c/SCSNxVxU
> Hack around the problem with retry messages

- src/main/java/uk/gov/ons/census/fwmtadapter/config/MessageConsumerConfig.java
- src/main/resources/application.yml
Some parts of RM are too quick.
Increased the retry delay from 1 second to 3 seconds.
Don't - this is to fix a theoretical problem so it can't really be tested.
Trello: https://trello.com/c/RExzTzH3
> Increase retry delay for eventual consistency

- src/main/java/uk/gov/ons/census/fwmtadapter/config/AppConfig.java
- src/main/java/uk/gov/ons/census/fwmtadapter/config/MessageConsumerConfig.java
- src/main/resources/application.yml
If we hit a problem when processing a Rabbit message, we aren't rolling back and handling retries properly - we are sending extra (duplicate) Rabbit messages, amongst other problems. This is quite fundamental to the reliable functioning of RM, so we can trust our code not to corrupt any data in the event of exceptions.
Added a `ChainedTransactionManager` per the suggestion of Dr David Syer in his article _Distributed transactions in Spring, with and without XA_ (http://www.infoworld.com/article/2077963/distributed-transactions-in-spring--with-and-without-xa.html)
It's super hard.
Suggestion: set the cache fetch count to 3,000 or more, and the timeout to 5 seconds or less, then run the AT scenario `Tranche 2 household case details to be sent to the Field Work Management Tool` with a …
> Fix Spring retries bug with transaction manager

- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/Event.java
We want to take advantage of Java's strong typing, and to use `OffsetDateTime` for date types, not strings.
Changed anywhere that was using a string for date/time/timestamp to use `OffsetDateTime`.
Run the ATs - should be zero regression.
Trello: https://trello.com/c/PbcNYiWe
> Use date type for dates

- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/messaging/CaseReceiver.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtActionInstruction.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiverTest.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/CaseReceiverTest.java
We want to record a property as secure so that future visits can be arranged if required
secureEstablishment flag changed from object to primitive type so it cannot be null
Updated tests
Build with other branches on card and run ATs
https://trello.com/c/4fnNI9lZ/1231-consume-secure-flag-on-newaddressreported-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?pageId=40216113
> Consume Secure Flag On New Address Reported

- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/FieldworkFollowup.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtActionInstruction.java
- src/main/java/uk/gov/ons/census/fwmtadapter/model/dto/fwmt/FwmtCancelActionInstruction.java
- src/test/java/uk/gov/ons/census/fwmtadapter/messaging/ActionFieldReceiverTest.java
When an AddressTypeChange event occurs where the new address is a CE Case, the ceActualResponses is null rather than 0 
Changed ceActualResponses from Integer to int so now defaults to 0 instead of null
Updated test
Maven clean install on branch and check image builds and tests pass
https://trello.com/c/DUgevj8y
> AddressTypeChange for CE Case ceActualResponses Defaulted to Zero
